### ISSUE TITLE
Exception in TFS implementation on simultaneous requests

### ISSUE THREAD

**Issue by g4rg** [PygmalionAI/aphrodite-engine#28]
I am hosting a multithreaded worker on horde.
If multiple jobs come in at roughly the same time, the following exception occurs.

If I reduce worker threads to 1, i.e. no simultaneous requests, this does not happen.
It also does not happen when using multiple threads *and* commenting out the part in `sampler.py` where it branches into `_apply_tfs`.

Tested on bare metal A100 40GB PCIe, model `PygmalionAI/pygmalion-2-13b`, fp16

```
    ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 27, in _raise_exception_on_finish
    task.result()
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 349, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 328, in engine_step
    request_outputs = await self.engine.step_async()
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 189, in step_async
    output = await self._run_workers_async(
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 214, in _run_workers_async
    output = executor(*args, **kwargs)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/aphrodite/aph032/aphrodite/task_handler/worker.py", line 324, in execute_model
    output = self.model(
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aphrodite/aph032/aphrodite/modeling/models/llama.py", line 296, in forward
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aphrodite/aph032/aphrodite/modeling/layers/sampler.py", line 66, in forward
    logits = _apply_tfs(logits, tfss)
  File "/home/aphrodite/aph032/aphrodite/modeling/layers/sampler.py", line 306, in _apply_tfs
    normalized_d2 = d2 / torch.sum(d2, dim=-1)
RuntimeError: The size of tensor a (31998) must match the size of tensor b (2) at non-singleton dimension 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    self,
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/aphrodite/aph032/aphrodite/endpoints/openai/api_server.py", line 523, in create_completion
    async for res in result_generator:
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 433, in generate
    raise e
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 427, in generate
    async for request_output in stream:
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 69, in __anext__
    raise result
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    self,
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/aphrodite/aph032/aphrodite/endpoints/openai/api_server.py", line 523, in create_completion
    async for res in result_generator:
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 433, in generate
    raise e
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 427, in generate
    async for request_output in stream:
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 69, in __anext__
    raise result
  File "/home/aphrodite/micromamba/envs/aph032/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 36, in _raise_exception_on_finish
    raise exc
  File "/home/aphrodite/aph032/aphrodite/engine/async_aphrodite.py", line 31, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
aphrodite.engine.async_aphrodite.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
```

**Comment by StefanGliga** [comment]
I think I know what's wrong, I'll start working on a fix right now

**Comment by AlpinDale** [comment]
Should be fixed by the latest commit. Please try again.

**Comment by g4rg** [comment]
Looks good now! Thanks.
