### ISSUE TITLE
Problem with request (before 0.5 works with no problem)

### ISSUE THREAD

**Issue by puppetm4st3r** [PygmalionAI/aphrodite-engine#311]
Hi, Iḿ trying the new release, and the next prompt throws an exception in the new engine, tryed many examples, also tried with many models and with many chat templates, all fails.

I leave the stack trace:
```
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=17, microseconds=169798), 'exception': None, 'extra': {}, 'file': 
(name='async_aphrodite.py', path='/workspace/aphrodite-engine/aphrodite/engine/async_aphrodite.py'), 'function': 
'add_request', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 495, 'message': 'Received request cmpl-
c7b48579f17e45ad9096d0d5950a65d7: prompt: \'<|im_start|>system\\\\n\\nYou are designed to help with a variety of tasks, 
from answering questions     to providing summaries to other types of analyses.\\n\\n## Tools\\nYou have access to a wide 
variety of tools. You are responsible for using\\nthe tools in any sequence you deem appropriate to complete the task at 
hand.\\nThis may require breaking the task into subtasks and using different tools\\nto complete each subtask.\\n\\nYou 
have access to the following tools:\\n> Tool Name: multiply\\nTool Description: Multiple two integers and returns the result 
integer\\nTool Args: {"type": "object", "properties": {"a": {"title": "A", "type": "integer"}, "b": {"title": "B", "type": "integer"}}, 
"required": ["a", "b"]}\\n\\n> Tool Name: add\\nTool Description: Add two integers and returns the result integer\\nTool Args: 
{"type": "object", "properties": {"a": {"title": "A", "type": "integer"}, "b": {"title": "B", "type": "integer"}}, "required": ["a", 
"b"]}\\n\\n\\n## Output Format\\nTo answer the question, please use the following format.\\n\\n```\\nThought: I need to use a 
tool to help me answer the question.\\nAction: tool name (one of multiply, add) if using a tool.\\nAction Input: the input to the 
tool, in a JSON format representing the kwargs (e.g. {"input": "hello world", "num_beams": 5})\\n```\\n\\nPlease ALWAYS 
start with a Thought.\\n\\nPlease use a valid JSON format for the Action Input. Do NOT do this {\\\'input\\\': \\\'hello world\\\', 
\\\'num_beams\\\': 5}.\\n\\nIf this format is used, the user will respond in the following format:\\n\\n```\\nObservation: tool 
response\\n```\\n\\nYou should keep repeating the above format until you have enough information\\nto answer the question 
without using any more tools. At that point, you MUST respond\\nin the one of the following two formats:\\n\\n```\\nThought: I 
can answer without using any more tools.\\nAnswer: [your answer here]\\n```\\n\\n```\\nThought: I cannot answer the 
question with the provided tools.\\nAnswer: Sorry, I cannot answer your query.\\n```\\n\\n## Current Conversation\\nBelow is 
the current conversation consisting of interleaving human and assistant 
messages.\\n\\n<|im_end|>\\\\n<|im_start|>user\\\\nWhat is 20+(2*4) ? Calculate step by step 
<|im_end|>\\\\n<|im_start|>assistant\', sampling params: SamplingParams(temperature=0.1, max_tokens=3391), prompt 
token ids: [1, 523, 28766, 321, 28730, 2521, 28766, 28767, 6574, 28756, 28711, 13, 1976, 460, 5682, 298, 1316, 395, 264, 
6677, 302, 9796, 28725, 477, 24402, 4224, 260, 298, 7501, 18062, 497, 298, 799, 4514, 302, 21974, 274, 28723, 13, 13, 
1064, 26258, 13, 1976, 506, 2735, 298, 264, 5335, 6677, 302, 7040, 28723, 995, 460, 7332, 354, 1413, 13, 1237, 7040, 
297, 707, 7768, 368, 340, 366, 7658, 298, 4160, 272, 3638, 438, 1021, 28723, 13, 3260, 993, 2699, 11313, 272, 3638, 778, 
1083, 21128, 304, 1413, 1581, 7040, 13, 532, 4160, 1430, 1083, 5553, 28723, 13, 13, 1976, 506, 2735, 298, 272, 2296, 
7040, 28747, 13, 28767, 12877, 6620, 28747, 17669, 346, 13, 6778, 10220, 28747, 9713, 4191, 989, 3113, 7850, 304, 
5723, 272, 1204, 11584, 13, 6778, 24997, 28747, 9830, 1123, 1264, 345, 2814, 548, 345, 10723, 1264, 9830, 28708, 1264, 
9830, 3901, 1264, 345, 28741, 548, 345, 1123, 1264, 345, 14296, 7706, 345, 28726, 1264, 9830, 3901, 1264, 345, 28760, 
548, 345, 1123, 1264, 345, 14296, 28739, 10781, 345, 10893, 1264, 7367, 28708, 548, 345, 28726, 2242, 28752, 13, 13, 
28767, 12877, 6620, 28747, 967, 13, 6778, 10220, 28747, 3301, 989, 3113, 7850, 304, 5723, 272, 1204, 11584, 13, 6778, 
24997, 28747, 9830, 1123, 1264, 345, 2814, 548, 345, 10723, 1264, 9830, 28708, 1264, 9830, 3901, 1264, 345, 28741, 
548, 345, 1123, 1264, 345, 14296, 7706, 345, 28726, 1264, 9830, 3901, 1264, 345, 28760, 548, 345, 1123, 1264, 345, 
14296, 28739, 10781, 345, 10893, 1264, 7367, 28708, 548, 345, 28726, 2242, 28752, 13, 13, 13, 1064, 15985, 18748, 13, 
1551, 4372, 272, 2996, 28725, 4665, 938, 272, 2296, 5032, 28723, 13, 13, 13940, 28832, 13, 1227, 1322, 28747, 315, 927, 
298, 938, 264, 3921, 298, 1316, 528, 4372, 272, 2996, 28723, 13, 3795, 28747, 3921, 1141, 325, 538, 302, 17669, 346, 
28725, 967, 28731, 513, 1413, 264, 3921, 28723, 13, 3795, 11232, 28747, 272, 2787, 298, 272, 3921, 28725, 297, 264, 
9292, 5032, 14030, 272, 23197, 325, 28706, 28723, 28721, 28723, 9830, 2537, 1264, 345, 21558, 1526, 548, 345, 2575, 
28730, 1105, 5322, 1264, 28705, 28782, 1542, 13, 13940, 28832, 13, 13, 12069, 10461, 26548, 28735, 1149, 395, 264, 
26142, 28723, 13, 13, 12069, 938, 264, 3716, 9292, 5032, 354, 272, 9624, 11232, 28723, 2378, 5457, 511, 456, 12012, 
2537, 1869, 464, 21558, 1526, 647, 464, 2575, 28730, 1105, 5322, 1869, 28705, 28782, 2051, 13, 13, 3381, 456, 5032, 
349, 1307, 28725, 272, 2188, 622, 9421, 297, 272, 2296, 5032, 28747, 13, 13, 13940, 28832, 13, 23044, 352, 28747, 3921, 
2899, 13, 13940, 28832, 13, 13, 1976, 1023, 1840, 5683, 1077, 272, 2747, 5032, 1996, 368, 506, 2066, 1871, 13, 532, 
4372, 272, 2996, 1671, 1413, 707, 680, 7040, 28723, 1794, 369, 1305, 28725, 368, 351, 11080, 9421, 13, 262, 272, 624, 
302, 272, 2296, 989, 23468, 28747, 13, 13, 13940, 28832, 13, 1227, 1322, 28747, 315, 541, 4372, 1671, 1413, 707, 680, 
7040, 28723, 13, 2820, 16981, 28747, 733, 19262, 4372, 1236, 28793, 13, 13940, 28832, 13, 13, 13940, 28832, 13, 1227, 
1322, 28747, 315, 3573, 4372, 272, 2996, 395, 272, 3857, 7040, 28723, 13, 2820, 16981, 28747, 19385, 28725, 315, 3573, 
4372, 574, 5709, 28723, 13, 13940, 28832, 13, 13, 1064, 10929, 1325, 25422, 13, 20548, 336, 349, 272, 1868, 7114, 
20922, 302, 791, 291, 1652, 2930, 304, 13892, 8570, 28723, 13, 13, 28789, 28766, 321, 28730, 416, 28766, 11266, 28711, 
28789, 28766, 321, 28730, 2521, 28766, 28767, 1838, 28756, 28711, 3195, 349, 28705, 28750, 28734, 24993, 28750, 
28736, 28781, 28731, 1550, 2984, 16914, 3707, 486, 3707, 523, 28766, 321, 28730, 416, 28766, 11266, 28711, 28789, 
28766, 321, 28730, 2521, 28766, 28767, 489, 11143], lora_request: None.', 'module': 'async_aphrodite', 'name': 
'aphrodite.engine.async_aphrodite', 'process': (id=1, name='MainProcess'), 'thread': (id=139723111862720, 
name='MainThread'), 'time': datetime(2024, 3, 12, 13, 25, 25, 450461, tzinfo=datetime.timezone(datetime.timedelta(0), 
'UTC'))}

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/loguru/_handler.py", line 164, in emit
    _, precomputed_format = self._memoize_dynamic_format(dynamic_format, ansi_level)
  File "/usr/local/lib/python3.10/dist-packages/loguru/_handler.py", line 14, in prepare_colored_format
    colored = Colorizer.prepare_format(format_)
  File "/usr/local/lib/python3.10/dist-packages/loguru/_colorizer.py", line 357, in prepare_format
    tokens, messages_color_tokens = Colorizer._parse_without_formatting(string)
  File "/usr/local/lib/python3.10/dist-packages/loguru/_colorizer.py", line 466, in _parse_without_formatting
    _, color_tokens = Colorizer._parse_without_formatting(
  File "/usr/local/lib/python3.10/dist-packages/loguru/_colorizer.py", line 466, in _parse_without_formatting
    _, color_tokens = Colorizer._parse_without_formatting(
  File "/usr/local/lib/python3.10/dist-packages/loguru/_colorizer.py", line 466, in _parse_without_formatting
    _, color_tokens = Colorizer._parse_without_formatting(
  File "/usr/local/lib/python3.10/dist-packages/loguru/_colorizer.py", line 438, in _parse_without_formatting
    raise ValueError("Max string recursion exceeded")
ValueError: Max string recursion exceeded
--- End of logging error ---

```
Any way the engine respond to the request with the expected generated text, seems to be something no so critical (seems)

Edit: Trying with 0.4.9 the prompt is renderized different, it seems that 0.5 add extra \ to scape strings or something like that, same prompt, same model, and the log shows a different prompt. **_In the system role you can see the differences_**

```
INFO 03-12 13:22:28 async_aphrodite.py:432] Received request cmpl-ef35020a14324f078f7d671f9e62c766: prompt: 
'<|im_start|>system\\n\nYou are designed to help with a variety of tasks, from answering questions     to providing 
summaries to other types of analyses.\n\n## Tools\nYou have access to a wide variety of tools. You are responsible for 
using\nthe tools in any sequence you deem appropriate to complete the task at hand.\nThis may require breaking the task 
into subtasks and using different tools\nto complete each subtask.\n\nYou have access to the following tools:\n> Tool Name: 
multiply\nTool Description: Multiple two integers and returns the result integer\nTool Args: {"type": "object", "properties": {"a": 
{"title": "A", "type": "integer"}, "b": {"title": "B", "type": "integer"}}, "required": ["a", "b"]}\n\n> Tool Name: add\nTool Description: 
Add two integers and returns the result integer\nTool Args: {"type": "object", "properties": {"a": {"title": "A", "type": "integer"}, 
"b": {"title": "B", "type": "integer"}}, "required": ["a", "b"]}\n\n\n## Output Format\nTo answer the question, please use the 
following format.\n\n```\nThought: I need to use a tool to help me answer the question.\nAction: tool name (one of multiply, 
add) if using a tool.\nAction Input: the input to the tool, in a JSON format representing the kwargs (e.g. {"input": "hello 
world", "num_beams": 5})\n```\n\nPlease ALWAYS start with a Thought.\n\nPlease use a valid JSON format for the Action 
Input. Do NOT do this {\'input\': \'hello world\', \'num_beams\': 5}.\n\nIf this format is used, the user will respond in the 
following format:\n\n```\nObservation: tool response\n```\n\nYou should keep repeating the above format until you have 
enough information\nto answer the question without using any more tools. At that point, you MUST respond\nin the one of 
the following two formats:\n\n```\nThought: I can answer without using any more tools.\nAnswer: [your answer 
here]\n```\n\n```\nThought: I cannot answer the question with the provided tools.\nAnswer: Sorry, I cannot answer your 
query.\n```\n\n## Current Conversation\nBelow is the current conversation consisting of interleaving human and assistant 
messages.\n\n<|im_end|>\\n<|im_start|>user\\nWhat is 20+(2*4) ? Calculate step by step 
<|im_end|>\\n<|im_start|>assistant', prefix_pos: None,sampling params: SamplingParams(n=1, best_of=1, 
presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.1, top_p=1.0, top_k=-1, top_a=0.0, 
min_p=0.0, tfs=1.0, eta_cutoff=0.0, epsilon_cutoff=0.0, typical_p=1.0, mirostat_mode=0, mirostat_tau=0.0, 
mirostat_eta=0.0, dynatemp_range=0.0, dynatemp_exponent=1.0, smoothing_factor=0.0, use_beam_search=False, 
length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, 
ignore_eos=False, max_tokens=3391, custom_token_bans=[], logprobs=None, prompt_logprobs=None, 
skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [1, 523, 28766, 321, 28730, 2521, 
28766, 28767, 6574, 28756, 28711, 13, 1976, 460, 5682, 298, 1316, 395, 264, 6677, 302, 9796, 28725, 477, 24402, 4224, 
260, 298, 7501, 18062, 497, 298, 799, 4514, 302, 21974, 274, 28723, 13, 13, 1064, 26258, 13, 1976, 506, 2735, 298, 264, 
5335, 6677, 302, 7040, 28723, 995, 460, 7332, 354, 1413, 13, 1237, 7040, 297, 707, 7768, 368, 340, 366, 7658, 298, 4160, 
272, 3638, 438, 1021, 28723, 13, 3260, 993, 2699, 11313, 272, 3638, 778, 1083, 21128, 304, 1413, 1581, 7040, 13, 532, 
4160, 1430, 1083, 5553, 28723, 13, 13, 1976, 506, 2735, 298, 272, 2296, 7040, 28747, 13, 28767, 12877, 6620, 28747, 
17669, 346, 13, 6778, 10220, 28747, 9713, 4191, 989, 3113, 7850, 304, 5723, 272, 1204, 11584, 13, 6778, 24997, 28747, 
9830, 1123, 1264, 345, 2814, 548, 345, 10723, 1264, 9830, 28708, 1264, 9830, 3901, 1264, 345, 28741, 548, 345, 1123, 
1264, 345, 14296, 7706, 345, 28726, 1264, 9830, 3901, 1264, 345, 28760, 548, 345, 1123, 1264, 345, 14296, 28739, 
10781, 345, 10893, 1264, 7367, 28708, 548, 345, 28726, 2242, 28752, 13, 13, 28767, 12877, 6620, 28747, 967, 13, 6778, 
10220, 28747, 3301, 989, 3113, 7850, 304, 5723, 272, 1204, 11584, 13, 6778, 24997, 28747, 9830, 1123, 1264, 345, 2814, 
548, 345, 10723, 1264, 9830, 28708, 1264, 9830, 3901, 1264, 345, 28741, 548, 345, 1123, 1264, 345, 14296, 7706, 345, 
28726, 1264, 9830, 3901, 1264, 345, 28760, 548, 345, 1123, 1264, 345, 14296, 28739, 10781, 345, 10893, 1264, 7367, 
28708, 548, 345, 28726, 2242, 28752, 13, 13, 13, 1064, 15985, 18748, 13, 1551, 4372, 272, 2996, 28725, 4665, 938, 272, 
2296, 5032, 28723, 13, 13, 13940, 28832, 13, 1227, 1322, 28747, 315, 927, 298, 938, 264, 3921, 298, 1316, 528, 4372, 
272, 2996, 28723, 13, 3795, 28747, 3921, 1141, 325, 538, 302, 17669, 346, 28725, 967, 28731, 513, 1413, 264, 3921, 
28723, 13, 3795, 11232, 28747, 272, 2787, 298, 272, 3921, 28725, 297, 264, 9292, 5032, 14030, 272, 23197, 325, 28706, 
28723, 28721, 28723, 9830, 2537, 1264, 345, 21558, 1526, 548, 345, 2575, 28730, 1105, 5322, 1264, 28705, 28782, 1542, 
13, 13940, 28832, 13, 13, 12069, 10461, 26548, 28735, 1149, 395, 264, 26142, 28723, 13, 13, 12069, 938, 264, 3716, 
9292, 5032, 354, 272, 9624, 11232, 28723, 2378, 5457, 511, 456, 12012, 2537, 1869, 464, 21558, 1526, 647, 464, 2575, 
28730, 1105, 5322, 1869, 28705, 28782, 2051, 13, 13, 3381, 456, 5032, 349, 1307, 28725, 272, 2188, 622, 9421, 297, 272, 
2296, 5032, 28747, 13, 13, 13940, 28832, 13, 23044, 352, 28747, 3921, 2899, 13, 13940, 28832, 13, 13, 1976, 1023, 1840, 
5683, 1077, 272, 2747, 5032, 1996, 368, 506, 2066, 1871, 13, 532, 4372, 272, 2996, 1671, 1413, 707, 680, 7040, 28723, 
1794, 369, 1305, 28725, 368, 351, 11080, 9421, 13, 262, 272, 624, 302, 272, 2296, 989, 23468, 28747, 13, 13, 13940, 
28832, 13, 1227, 1322, 28747, 315, 541, 4372, 1671, 1413, 707, 680, 7040, 28723, 13, 2820, 16981, 28747, 733, 19262, 
4372, 1236, 28793, 13, 13940, 28832, 13, 13, 13940, 28832, 13, 1227, 1322, 28747, 315, 3573, 4372, 272, 2996, 395, 272, 
3857, 7040, 28723, 13, 2820, 16981, 28747, 19385, 28725, 315, 3573, 4372, 574, 5709, 28723, 13, 13940, 28832, 13, 13, 
1064, 10929, 1325, 25422, 13, 20548, 336, 349, 272, 1868, 7114, 20922, 302, 791, 291, 1652, 2930, 304, 13892, 8570, 
28723, 13, 13, 28789, 28766, 321, 28730, 416, 28766, 11266, 28711, 28789, 28766, 321, 28730, 2521, 28766, 28767, 
1838, 28756, 28711, 3195, 349, 28705, 28750, 28734, 24993, 28750, 28736, 28781, 28731, 1550, 2984, 16914, 3707, 486, 
3707, 523, 28766, 321, 28730, 416, 28766, 11266, 28711, 28789, 28766, 321, 28730, 2521, 28766, 28767, 489, 11143], 
lora_request: None.

```

**Comment by AlpinDale** [comment]
Related: #309

Should hopefully be fixed sometime soon.

**Comment by puppetm4st3r** [comment]
Thanks for the information, will close the issue.
