### ISSUE TITLE
`RuntimeError: CUDA unknown error` on Runpod (but works fine on local machine)

### ISSUE THREAD

**Issue by josephrocca** [PygmalionAI/aphrodite-engine#317]
This works fine on my local machine, but if I put `alpindale/aphrodite-engine` in as "Docker Image Name" on Runpod with a RTX 4090, and set the volume mount path to `/app`, then I get this error:
```
2024-03-13T13:36:25.168094375Z [FATAL tini (7)] exec /app/aphrodite-engine/docker/entrypoint.sh failed: No such file or directory
```
Looking at the [Dockerfile](https://github.com/PygmalionAI/aphrodite-engine/blob/50c0875c3286665738fd9ef85ea68639cef24395/docker/Dockerfile#L20), that error does kinda make sense (from the perspective of a docker noob), since the repo was cloned to `/tmp/aphrodite-engine` and then deleted. I'm not experienced enough with this stuff to know how it gets to `/app/aphrodite-engine` so that it works fine on my local machine. If I change the volume mount path to something else like `/volume`, then that seems to fix it, but I then get this error:
```
2024-03-13T13:40:40.885775454Z Starting Aphrodite Engine API server...
2024-03-13T13:40:40.885865114Z + exec python3 -m aphrodite.endpoints.openai.api_server --host 0.0.0.0 --port 5000 --download-dir /app/tmp/hub --enforce-eager
2024-03-13T13:40:42.730822161Z INFO:     Initializing the Aphrodite Engine (v0.5.0) with the following config:
2024-03-13T13:40:42.730838301Z INFO:     Model = 'EleutherAI/pythia-70m-deduped'
2024-03-13T13:40:42.730841261Z INFO:     DataType = torch.float16
2024-03-13T13:40:42.730843961Z INFO:     Model Load Format = auto
2024-03-13T13:40:42.730846471Z INFO:     Number of GPUs = 1
2024-03-13T13:40:42.730848921Z INFO:     Disable Custom All-Reduce = False
2024-03-13T13:40:42.730851141Z INFO:     Quantization Format = None
2024-03-13T13:40:42.730853271Z INFO:     Context Length = 2048
2024-03-13T13:40:42.730855451Z INFO:     Enforce Eager Mode = True
2024-03-13T13:40:42.730857601Z INFO:     KV Cache Data Type = auto
2024-03-13T13:40:42.730859621Z INFO:     KV Cache Params Path = None
2024-03-13T13:40:42.730862071Z INFO:     Device = cuda
2024-03-13T13:40:44.398675257Z Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-03-13T13:40:44.417161313Z Traceback (most recent call last):
2024-03-13T13:40:44.417174093Z   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-03-13T13:40:44.417176513Z     return _run_code(code, main_globals, None,
2024-03-13T13:40:44.417178273Z   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-03-13T13:40:44.417180393Z     exec(code, run_globals)
2024-03-13T13:40:44.417182453Z   File "/app/aphrodite-engine/aphrodite/endpoints/openai/api_server.py", line 561, in <module>
2024-03-13T13:40:44.417184263Z     engine = AsyncAphrodite.from_engine_args(engine_args)
2024-03-13T13:40:44.417185943Z   File "/app/aphrodite-engine/aphrodite/engine/async_aphrodite.py", line 676, in from_engine_args
2024-03-13T13:40:44.417188133Z     engine = cls(parallel_config.worker_use_ray,
2024-03-13T13:40:44.417190063Z   File "/app/aphrodite-engine/aphrodite/engine/async_aphrodite.py", line 341, in __init__
2024-03-13T13:40:44.417191883Z     self.engine = self._init_engine(*args, **kwargs)
2024-03-13T13:40:44.417193573Z   File "/app/aphrodite-engine/aphrodite/engine/async_aphrodite.py", line 410, in _init_engine
2024-03-13T13:40:44.417195483Z     return engine_class(*args, **kwargs)
2024-03-13T13:40:44.417197173Z   File "/app/aphrodite-engine/aphrodite/engine/aphrodite_engine.py", line 113, in __init__
2024-03-13T13:40:44.417198883Z     self._init_workers()
2024-03-13T13:40:44.417201173Z   File "/app/aphrodite-engine/aphrodite/engine/aphrodite_engine.py", line 154, in _init_workers
2024-03-13T13:40:44.417202853Z     self._run_workers("init_model")
2024-03-13T13:40:44.417204533Z   File "/app/aphrodite-engine/aphrodite/engine/aphrodite_engine.py", line 1025, in _run_workers
2024-03-13T13:40:44.417206143Z     driver_worker_output = getattr(self.driver_worker,
2024-03-13T13:40:44.417207793Z   File "/app/aphrodite-engine/aphrodite/task_handler/worker.py", line 93, in init_model
2024-03-13T13:40:44.417209403Z     torch.cuda.set_device(self.device)
2024-03-13T13:40:44.417211033Z   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 408, in set_device
2024-03-13T13:40:44.417212673Z     torch._C._cuda_setDevice(device)
2024-03-13T13:40:44.417214343Z   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 302, in _lazy_init
2024-03-13T13:40:44.417215953Z     torch._C._cuda_init()
2024-03-13T13:42:17.392754775Z RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
```
The only other options in the Runpod template are env variable `NUMBA_CACHE_DIR=/tmp/numba_cache` to solve [this issue](https://github.com/PygmalionAI/aphrodite-engine/issues/310#issuecomment-1993443359) and `ENFORCE_EAGER=true` to prevent OOM.

As I mentioned, it works fine on my local machine, and the error isn't giving me much of a clue, so I'm not sure what's going on here.

Wondering if anyone knows what might be causing this?

![image](https://github.com/PygmalionAI/aphrodite-engine/assets/1167575/0e29b17f-9805-4b9a-815d-992af35787e8)

**Comment by AlpinDale** [comment]
Not sure what's happening, but I updated the runpod image. You can try it [here](https://runpod.io/console/gpu-cloud?template=wtxeviosoe&ref=pj92bzrz). Seems to work fine for me with mistral 7b (takes a bit to start because I added the `--load-in-4bit` argument).

**Comment by josephrocca** [comment]
Welp, I have no idea what I was doing originally, but I copied your template and swapped the model, and it works fine now. Thanks!
