### ISSUE TITLE
CUDA illegal memory access when loading 70b AWQ with RoPE

### ISSUE THREAD

**Issue by g4rg** [PygmalionAI/aphrodite-engine#50]
I'm using RoPE by editing the model's config file.
```
"rope_scaling": {"type":"dynamic", "factor": 2.0},
```
It seems to work for 13b and 20b llama2 models.
No success with 70b AWQ + the snippet above.
```
$ python -m aphrodite.endpoints.api_server_kobold --model TheBloke/Xwin-LM-70B-V0.1-AWQ -q awq
INFO 10-06 19:25:44 aphrodite_engine.py:72] Initializing an LLM engine with config: model='TheBloke/Xwin-LM-70B-V0.1-AWQ', tokenizer='TheBloke/Xwin-LM-70B-V0.1-AWQ', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=awq, seed=0)
Traceback (most recent call last):
  File "/home/aphrodite/micromamba/envs/aphdev/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aphrodite/micromamba/envs/aphdev/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aphrodite/aphdev/aphrodite/endpoints/api_server_kobold.py", line 214, in <module>
    engine = AsyncAphrodite.from_engine_args(engine_args)
  File "/home/aphrodite/aphdev/aphrodite/engine/async_aphrodite.py", line 484, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/home/aphrodite/aphdev/aphrodite/engine/async_aphrodite.py", line 268, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/aphrodite/aphdev/aphrodite/engine/async_aphrodite.py", line 304, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/aphrodite/aphdev/aphrodite/engine/aphrodite_engine.py", line 110, in __init__
    self._init_cache()
  File "/home/aphrodite/aphdev/aphrodite/engine/aphrodite_engine.py", line 190, in _init_cache
    num_blocks = self._run_workers(
  File "/home/aphrodite/aphdev/aphrodite/engine/aphrodite_engine.py", line 691, in _run_workers
    output = executor(*args, **kwargs)
  File "/home/aphrodite/micromamba/envs/aphdev/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/aphrodite/aphdev/aphrodite/task_handler/worker.py", line 109, in profile_num_available_blocks
    self.model(
  File "/home/aphrodite/micromamba/envs/aphdev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aphrodite/aphdev/aphrodite/modeling/models/llama.py", line 299, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/home/aphrodite/micromamba/envs/aphdev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aphrodite/aphdev/aphrodite/modeling/models/llama.py", line 259, in forward
    hidden_states = layer(
  File "/home/aphrodite/micromamba/envs/aphdev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aphrodite/aphdev/aphrodite/modeling/models/llama.py", line 206, in forward
    hidden_states = self.self_attn(
  File "/home/aphrodite/micromamba/envs/aphdev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aphrodite/aphdev/aphrodite/modeling/models/llama.py", line 155, in forward
    attn_output = self.attn(positions, q, k, v, k_cache, v_cache,
  File "/home/aphrodite/micromamba/envs/aphdev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aphrodite/aphdev/aphrodite/modeling/layers/attention.py", line 335, in forward
    return super().forward(
  File "/home/aphrodite/aphdev/aphrodite/modeling/layers/attention.py", line 215, in forward
    self.multi_query_kv_attention(
  File "/home/aphrodite/aphdev/aphrodite/modeling/layers/attention.py", line 119, in multi_query_kv_attention
    key = torch.repeat_interleave(key, self.num_queries_per_kv, dim=1)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by AlpinDale** [comment]
Try reducing the `--max-num-batched-tokens` and try again.

**Comment by g4rg** [comment]
Same thing with `--max-num-batched-token 8192`.
This is on A100 80GB.

**Comment by AlpinDale** [comment]
I'm getting the same error with 34B-AWQ. Looks like AWQ kernels don't support CodeLlama properly? Investigating now.

**Comment by StefanGliga** [comment]
Could it be that GQA+AWQ+NTK RoPE scaling all together are somehow conflicting?

**Comment by AlpinDale** [comment]
Seems like it. GPTQ kernels behave as normal though. I'll try without the RoPE scaling with 34B in a bit.

**Comment by g4rg** [comment]
34B fp16 + RoPE works

**Comment by AlpinDale** [comment]
Sorry I forgot about this issue. It should be fixed by now. Have you run into any problems with 70B AWQ + RoPE lately? @g4rg

**Comment by g4rg** [comment]
Yes, it has been working for a while now. Sorry, forgot to update.
