### ISSUE TITLE
[Installation]: Docker Build: No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda' aphrodite-engine (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by derpyhue** [PygmalionAI/aphrodite-engine#578]
### Your current environment

```text
711.8 Building wheels for collected packages: aphrodite-engine, wavedrom
711.8   Building editable for aphrodite-engine (pyproject.toml): started
713.2   Building editable for aphrodite-engine (pyproject.toml): finished with status 'error'
713.3   error: subprocess-exited-with-error
713.3
713.3   × Building editable for aphrodite-engine (pyproject.toml) did not run successfully.
713.3   │ exit code: 1
713.3   ╰─> [117 lines of output]
713.3       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
713.3       running editable_wheel
713.3       creating /tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info
713.3       writing /tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info/PKG-INFO
713.3       writing dependency_links to /tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info/dependency_links.txt
713.3       writing entry points to /tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info/entry_points.txt
713.3       writing requirements to /tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info/requires.txt
713.3       writing top-level names to /tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info/top_level.txt
713.3       writing manifest file '/tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info/SOURCES.txt'
713.3       reading manifest file '/tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info/SOURCES.txt'
713.3       reading manifest template 'MANIFEST.in'
713.3       adding license file 'LICENSE'
713.3       writing manifest file '/tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine.egg-info/SOURCES.txt'
713.3       creating '/tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine-0.5.3.dist-info'
713.3       creating /tmp/pip-wheel-alb9mf3z/.tmp-oztxfiut/aphrodite_engine-0.5.3.dist-info/WHEEL
713.3       running build_py
713.3       running build_ext
713.3       Traceback (most recent call last):
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py", line 153, in run
713.3           self._create_wheel_file(bdist_wheel)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py", line 355, in _create_wheel_file
713.3           files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py", line 278, in _run_build_commands
713.3           self._run_build_subcommands()
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py", line 305, in _run_build_subcommands
713.3           self.run_command(name)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
713.3           self.distribution.run_command(command)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 945, in run_command
713.3           super().run_command(command)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 989, in run_command
713.3           cmd_obj.run()
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 93, in run
713.3           _build_ext.run(self)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
713.3           self.build_extensions()
713.3         File "<string>", line 185, in build_extensions
713.3         File "<string>", line 153, in configure
713.3         File "<string>", line 65, in compute_num_jobs
713.3       ValueError: invalid literal for int() with base 10: ''
713.3       /tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py:989: _DebuggingTips: Problem in editable installation.
713.3       !!
713.3
713.3               ********************************************************************************
713.3               An error happened while installing `aphrodite-engine` in editable mode.
713.3
713.3               The following steps are recommended to help debug this problem:
713.3
713.3               - Try to install the project normally, without using the editable mode.
713.3                 Does the error still persist?
713.3                 (If it does, try fixing the problem before attempting the editable mode).
713.3               - If you are using binary extensions, make sure you have all OS-level
713.3                 dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
713.3               - Try the latest version of setuptools (maybe the error was already fixed).
713.3               - If you (or your project dependencies) are using any setuptools extension
713.3                 or customization, make sure they support the editable mode.
713.3
713.3               After following the steps above, if the problem still persists and
713.3               you think this is related to how setuptools handles editable installations,
713.3               please submit a reproducible example
713.3               (see https://stackoverflow.com/help/minimal-reproducible-example) to:
713.3
713.3                   https://github.com/pypa/setuptools/issues
713.3
713.3               See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
713.3               ********************************************************************************
713.3
713.3       !!
713.3         cmd_obj.run()
713.3       Traceback (most recent call last):
713.3         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
713.3           main()
713.3         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
713.3           json_out['return_val'] = hook(**hook_input['kwargs'])
713.3         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
713.3           return hook(wheel_directory, config_settings, metadata_directory)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 453, in build_editable
713.3           return self._build_with_temp_dir(
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
713.3           self.run_setup()
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 313, in run_setup
713.3           exec(code, locals())
713.3         File "<string>", line 424, in <module>
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 108, in setup
713.3           return distutils.core.setup(**attrs)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 184, in setup
713.3           return run_commands(dist)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 200, in run_commands
713.3           dist.run_commands()
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 970, in run_commands
713.3           self.run_command(cmd)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 945, in run_command
713.3           super().run_command(command)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 989, in run_command
713.3           cmd_obj.run()
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py", line 153, in run
713.3           self._create_wheel_file(bdist_wheel)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py", line 355, in _create_wheel_file
713.3           files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py", line 278, in _run_build_commands
713.3           self._run_build_subcommands()
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py", line 305, in _run_build_subcommands
713.3           self.run_command(name)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
713.3           self.distribution.run_command(command)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 945, in run_command
713.3           super().run_command(command)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 989, in run_command
713.3           cmd_obj.run()
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 93, in run
713.3           _build_ext.run(self)
713.3         File "/tmp/pip-build-env-x94y61qu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
713.3           self.build_extensions()
713.3         File "<string>", line 185, in build_extensions
713.3         File "<string>", line 153, in configure
713.3         File "<string>", line 65, in compute_num_jobs
713.3       ValueError: invalid literal for int() with base 10: ''
713.3       [end of output]
713.3
713.3   note: This error originates from a subprocess, and is likely not a problem with pip.
713.3   ERROR: Failed building editable for aphrodite-engine
713.3   Building wheel for wavedrom (setup.py): started
713.4   Building wheel for wavedrom (setup.py): finished with status 'done'
713.4   Created wheel for wavedrom: filename=wavedrom-2.0.3.post3-py2.py3-none-any.whl size=30071 sha256=c9632d41830a05b1293d53cabc7df78c7bbf11632a21a6a42fdee0a693dbaac1
713.4   Stored in directory: /tmp/pip-ephem-wheel-cache-5tztcr15/wheels/9c/52/8c/38b454b42f712f325e26f633287484c7dc1ad469e1580c5954
713.4 Successfully built wavedrom
713.4 Failed to build aphrodite-engine
713.6 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (aphrodite-engine)

```

### How did you install Aphrodite?

```sh
docker compose -f docker/docker-compose.yml build
```

Not sure what is wrong. when using run nvcc --version in the dockerfile it gives:
 nvcc: NVIDIA (R) Cuda compiler driver
 => => # Copyright (c) 2005-2023 NVIDIA Corporation
 => => # Built on Mon_Apr__3_17:16:06_PDT_2023
 => => # Cuda compilation tools, release 12.1, V12.1.105
 => => # Build cuda_12.1.r12.1/compiler.32688072_0
 
When including a symlink ln -s /usr/local/cuda-12.1 /usr/local/cuda with a install of cuda 12.1 it still does not pick it up.

I'm using a 3060 RTX
Ryzen 3600
Ubuntu headless 24.04

Thank you for your time!

**Comment by derpyhue** [comment]
Working from rc_054 works perfectly!
Looking good 👍
