### ISSUE TITLE
[Bug]: Error using gemma models

### ISSUE THREAD

**Issue by Abdulhanan535** [PygmalionAI/aphrodite-engine#623]
### Your current environment

```
Kaggle.
```

### 🐛 Describe the bug
```
WARNING:  Casting torch.bfloat16 to torch.float16.
WARNING:  Gemma 2 uses sliding window attention for every odd layer, which is currently not 
supported by Aphrodite. Disabling sliding window and capping the max length to the sliding window 
size (4096).
WARNING:  bitsandbytes quantization is not fully optimized yet. The speed can be slower than 
non-quantized models.
WARNING:  Casting torch.bfloat16 to torch.float16.
WARNING:  bitsandbytes quantization is not fully optimized yet. The speed can be slower than 
non-quantized models.
INFO:     -------------------------------------------------------------------------------------
INFO:     Initializing Aphrodite Engine (v0.6.0 commit 75122b2) with the following config:
INFO:     Model = 'unsloth/gemma-2-9b-it-bnb-4bit'
INFO:     DataType = torch.float16
INFO:     Tensor Parallel Size = 1
INFO:     Pipeline Parallel Size = 1
INFO:     Disable Custom All-Reduce = False
INFO:     Quantization Format = 'bitsandbytes'
INFO:     Context Length = 4096
INFO:     Enforce Eager Mode = True
INFO:     Prefix Caching = False
INFO:     Device = device(type='cuda')
INFO:     Guided Decoding Backend = DecodingConfig(guided_decoding_backend='outlines')
INFO:     -------------------------------------------------------------------------------------
INFO:     Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO:     Using XFormers backend.
/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
INFO:     Loading model unsloth/gemma-2-9b-it-bnb-4bit...
INFO:     Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO:     Using XFormers backend.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/endpoints/openai/rpc/server.py", line 204, in run_rpc_server
    server = AsyncEngineRPCServer(async_engine_args, port)
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/endpoints/openai/rpc/server.py", line 23, in __init__
    self.engine = AsyncAphrodite.from_engine_args(async_engine_args)
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/engine/async_aphrodite.py", line 470, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/engine/async_aphrodite.py", line 379, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/engine/async_aphrodite.py", line 550, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/engine/aphrodite_engine.py", line 243, in __init__
    self.model_executor = executor_class(
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/executor/executor_base.py", line 47, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/executor/gpu_executor.py", line 36, in _init_executor
    self.driver_worker.load_model()
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/task_handler/worker.py", line 146, in load_model
    self.model_runner.load_model()
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/task_handler/model_runner.py", line 730, in load_model
    self.model = get_model(model_config=self.model_config,
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/modeling/model_loader/__init__.py", line 21, in get_model
    return loader.load_model(model_config=model_config,
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/modeling/model_loader/loader.py", line 323, in load_model
    model = _initialize_model(model_config, self.load_config,
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/modeling/model_loader/loader.py", line 153, in _initialize_model
    return model_class(config=model_config.hf_config,
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/modeling/models/gemma2.py", line 327, in __init__
    self.model = Gemma2Model(config, cache_config, quant_config)
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/modeling/models/gemma2.py", line 255, in __init__
    self.layers = nn.ModuleList([
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/modeling/models/gemma2.py", line 256, in <listcomp>
    Gemma2DecoderLayer(layer_idx, config, cache_config, quant_config)
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/modeling/models/gemma2.py", line 181, in __init__
    self.self_attn = Gemma2Attention(
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/modeling/models/gemma2.py", line 147, in __init__
    self.attn = Attention(self.num_heads,
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/attention/layer.py", line 84, in __init__
    self.impl = impl_cls(num_heads, head_size, scale, num_kv_heads,
  File "/usr/local/lib/python3.10/dist-packages/aphrodite/attention/backends/xformers.py", line 416, in __init__
    raise ValueError(
ValueError: XFormers does not support attention logits soft capping.
```

**Comment by AlpinDale** [comment]
Attention soft-capping is not supported on xformers, and Turing cards (T4) do not support flash attention. For now, you'll need to install flashinfer instead. Please install the appropriate wheel here for your python version. https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.1.2

Copy the url for the correct one and run `pip install <the http url>`

**Comment by Abdulhanan535** [comment]
and about the gemma 2 4096 ctx issue?

**Comment by Abdulhanan535** [comment]
what cuda version and torch version should i use?

**Comment by Abdulhanan535** [comment]
it has python 3.10 
`Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> `

**Comment by Abdulhanan535** [comment]
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[3], line 116
    114 get_ipython().run_line_magic('pip', 'install aphrodite-engine --extra-index-url https://downloads.pygmalion.chat/whl > /dev/null 2>&1')
    115 get_ipython().run_line_magic('pip', 'install [https://github.com/flashinfer-ai/flashinfer/releases/download/v0.1.2/flashinfer-0.1.2+cu121torch2.4-cp310-cp310-linux_x86_64.whl](https://github.com/flashinfer-ai/flashinfer/releases/download/v0.1.2/flashinfer-0.1.2+cu121torch2.4-cp310-cp310-linux_x86_64.whl%3C/span%3E%3Cspan) style="color:rgb(175,0,0)">')
--> 116 APHRODITE_ATTENTION_BACKEND=flashinfer
    117 get_ipython().system('echo "Installation successful! Starting the engine now."')
    120 #RAY

NameError: name 'flashinfer' is not defined`



#Aphrodite Engine
%pip show aphrodite-engine &> /dev/null && echo "Existing Aphrodite Engine installation found. Updating..." && pip uninstall aphrodite-engine -q -y
!echo "Installing/Updating the Aphrodite Engine, this may take a while..."
%pip install aphrodite-engine --extra-index-url https://downloads.pygmalion.chat/whl > /dev/null 2>&1
%pip install https://github.com/flashinfer-ai/flashinfer/releases/download/v0.1.2/flashinfer-0.1.2+cu121torch2.4-cp310-cp310-linux_x86_64.whl
APHRODITE_ATTENTION_BACKEND=flashinfer
!echo "Installation successful! Starting the engine now."

**Comment by AlpinDale** [comment]
You should prefix your aphrodite launch command with that.

**Comment by Abdulhanan535** [comment]
`2024-09-04 16:30:46.291 | WARNING  | aphrodite._core_ext:<module>:174 - Failed to import from aphrodite._core_C with /opt/conda/lib/python3.10/site-packages/aphrodite/_core_C.abi3.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
Traceback (most recent call last):
  File "/opt/conda/bin/aphrodite", line 5, in <module>
    from aphrodite.endpoints.cli import main
  File "/opt/conda/lib/python3.10/site-packages/aphrodite/__init__.py", line 5, in <module>
    from aphrodite.endpoints.llm import LLM
  File "/opt/conda/lib/python3.10/site-packages/aphrodite/endpoints/llm.py", line 10, in <module>
    from aphrodite.common.utils import Counter, deprecate_kwargs
  File "/opt/conda/lib/python3.10/site-packages/aphrodite/common/utils.py", line 29, in <module>
    from aphrodite import _custom_ops as ops
  File "/opt/conda/lib/python3.10/site-packages/aphrodite/_custom_ops.py", line 8, in <module>
    from aphrodite._core_ext import ScalarType
  File "/opt/conda/lib/python3.10/site-packages/aphrodite/_core_ext.py", line 176, in <module>
    ScalarType = torch.classes._core_C.ScalarType
  File "/opt/conda/lib/python3.10/site-packages/torch/_classes.py", line 13, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
RuntimeError: Tried to instantiate class '_core_C.ScalarType', but it does not exist! Ensure that it is registered via torch::class_`

**Comment by Abdulhanan535** [comment]
anyone?

**Comment by Abdulhanan535** [comment]
anyone??

**Comment by Abdulhanan535** [comment]
have you found a way?

> I get the same error with GGUF Gemma2-27b-it on kaggle.

**Comment by Abdulhanan535** [comment]
can we just get gemma2forcasualLm support on the v0.5.3 version?

**Comment by kristaller486** [comment]
Looks like this error does not depend on model arch. I get it with Mistral-NeMo gguf model. I do not know how to fix it.

**Comment by Abdulhanan535** [comment]
the older versions were working fine right? mine did work fine..

**Comment by Abdulhanan535** [comment]
@AlpinDale

**Comment by Abdulhanan535** [comment]
Got the fix

simply add --force-reinstall to pip install aphrodite-engine

lol

**Comment by drdown33** [comment]
> Attention soft-capping is not supported on xformers, and Turing cards (T4) do not support flash attention. For now, you'll need to install flashinfer instead. Please install the appropriate wheel here for your python version. https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.1.2
> 
> Copy the url for the correct one and run `pip install <the http url>`
> 
> After that, launch aphrodite with `APHRODITE_ATTENTION_BACKEND=flashinfer aphrodite run ...`

This package appears to only be available for linux. Is there any solution to this problem for those running aphrodite-engine on Windows?

**Comment by Abdulhanan535** [comment]
RIP for them. XD
